language: lisp

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

#matrix:
#  allow_failures:
#    - env: LISP=sbcl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | sh;
    fi     

script:
  - cl-launch -i "(ql:quickload :cl-ngxmpp-test) (cl-ngxmpp-test:run-all-tests)"
  - cl-launch -i "(ql:quickload :cl-ngxmpp-client-test) (cl-ngxmpp-client-test:run-all-tests)"; [ $? -eq 1 ]
